[OpenAI]
OPENAI_ORGANIZATION_ID = "org-O0Op3NUhIeC4pkgzUS4tQcHD"
OPENAI_PROJECT_ID = "proj_Q9yK9QnTwdOzMVoYsweFQPfL"
OPENAI_API_KEY = "sk-svcacct-NA4k7jNb-KYZBdxGjrDK0wi0FGbvleRGLZAtytlTJ5aufxLEoRUnikanQ7EkVLIYfMEhtzfbT3BlbkFJoLpFwb2EH6homsWXSRUb5cPxXPREDfkaqW3QtTse9_s9E8j0BgqgMuHxw5K7Q0IexZzYocgA"